import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import your custom application layout shells
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // GTmetrix performance optimization: Eliminates text flash & layout shift shifts
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // GTmetrix performance optimization
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/4biz_logo.png", // Sets the main favicon/site icon
    shortcut: "/4biz_logo.png", // Sets the shortcut icon for bookmark bars
    apple: "/4biz_logo.png", // Sets the icon for iOS home screen bookmarks
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      style={{ scrollBehavior: "smooth" }}
    >
      <head>
        {/* Next.js compliant raw CSS injection to completely obliterate the Google translate widgets */}
        <style
          dangerouslySetInnerHTML={{
            __html: `
              .skiptranslate,
              #goog-gt-tt,
              .goog-te-banner-frame,
              .goog-te-gadget,
              .goog-te-gadget-simple,
              .goog-te-menu-value,
              iframe.goog-te-banner-frame,
              body > .skiptranslate,
              [class*="goog-te"],
              #google_translate_element {
                display: none !important;
                visibility: hidden !important;
                opacity: 0 !important;
                pointer-events: none !important;
                height: 0 !important;
                width: 0 !important;
              }
              body {
                top: 0 !important;
                position: static !important;
              }
            `,
          }}
        />
      </head>
      <body className="w-full min-h-screen bg-zinc-950 text-white overflow-x-hidden block">
        {/* Persistent App Shell Header Navigation System */}
        <Header />

        {/* Dynamic Route Viewport Workspace Wrapper - changed to relative block for natural layouts */}
        <main className="w-full relative clear-both block">
          {children}
        </main>

        {/* Responsive Interactive Footer Foundation */}
        <Footer />
      </body>
    </html>
  );
}